### ISSUE TITLE
Write tests for zip_codes

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/doggie#1]
We have 128 regular expression for 128 countries, but i wrote the tests only for 2 countries. So, we need to implement tests for for the remaining 126 countries.

**Comment by lk-geimfari** [comment]
@Battleroid Can you help me with `:us`?

**Comment by Battleroid** [comment]
I actually have zero experience with elixir so I'm not sure if I'd be much help.

**Comment by fcapovilla** [comment]
I implemented the tests for the remaining countries, when possible.
More details in the pull request.

**Comment by kinson** [comment]
Was browsing through hacktoberfest issues and saw this issue, glad someone was able to tackle it! Should it be closed now though?

**Comment by lk-geimfari** [comment]
@kinson Of course! Thanks for remind me.
